plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'com.roni.library.service'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
        consumerProguardFiles "consumer-rules.pro"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.7.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation 'com.github.infoadmstudio2020-cyber:native-logger-sdk:v1.0.1'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId    = 'com.roni.library.service'
                artifactId = 'native-service-sdk'
                version    = '1.0.1'

                pom {
                    name        = 'NativeServiceSDK'
                    description = ''
                    url         = 'https://github.com/infoadmstudio2020-cyber/native-service-sdk'
                    licenses {
                        license {
                            name = 'Apache-2.0'
                        }
                    }
                    developers {
                        developer {
                            name = 'infoadmstudio2020-cyber'
                        }
                    }
                }
            }
        }
    }

    // Configure task ordering without circular or recursive execution
    tasks.matching { it.name in ['publishToMavenLocal', 'publishReleasePublicationToMavenLocal'] }.configureEach {
        mustRunAfter(tasks.matching { it.name == 'assembleRelease' })
    }
}
